### ISSUE TITLE
Travis is not testing everything

### ISSUE THREAD

**Issue by pancetta** [JLESC/jlesc.github.io#101] opened 2016-02-19 09:16 UTC
We had two PRs (#94 and #100) where Travis did not run tests automatically.. why is that?

**Comment by pancetta** [comment] 2016-02-19 09:24
OK, it did run tests, but Github does not show the results, see https://travis-ci.org/JLESC/jlesc.github.io

**Comment by torbjoernk** [comment] 2016-02-19 09:27
This seems to be caused by some random communication problems between GitHub and Travis.

You linked Travis' build of your merge push. That linked Travis job was not testing the PR, but deploying.

In both cases mentioned above, GitHub didn't trigger Travis or the trigger didn't went through to Travis.

For future reference here are three links you might want to check out to debug such problems:
- [list of GitHub-to-Travis requests and Travis' notes on why it triggered a build or not](https://travis-ci.org/JLESC/jlesc.github.io/requests)
- [general status of Travis](https://www.traviscistatus.com/)
- [general status of GitHub](https://status.github.com/)

You can always re-trigger a GitHub-to-Travis request by updating the branch of the PR. This must be done by the person who opened the PR. An empty commit (`git commit --allow-empty -m'trigger Travis'`) is fine.

**Note**: Pushes which contain a commit where the commit message contains the string "`[ci skip]`" will always be ignored by Travis. It will tell you so on the above linked request list page.

**Comment by torbjoernk** [comment] 2016-02-22 08:18
I've added a note on this issue on the wiki's Troubleshooting page and will close this issue now.

**Closed as completed by torbjoernk** 2016-02-22 08:18 UTC
Labels: bug, question, wontfix
